apps/testing: Add a cmocka framework for network testing
open-vela/apps pull request #28
Opened 2024-12-24 13:10 UTC by zs39

## Summary
Provides a network automated testing framework, including the main directory structure and Makefile, CMakeLists, Kconfig and other files such as tcp.

## Impact
N/A

## Testing
qemu environment test

2024-12-24 15:45 UTC, GUIDINGLI commented on testing/nettest/Kconfig
> +config TESTING_NET_TCP
what's the purpose of this marco ? keep only TESTING_NET_TEST ?

2024-12-25 01:37 UTC, zs39 commented on testing/nettest/Kconfig
> +config TESTING_NET_TCP
> what's the purpose of this marco ? keep only TESTING_NET_TEST ?

In the future, test cases will be grouped according to network protocols. Should I remove this macro in this patch?

2024-12-25 02:40 UTC, wengzhe requested changes

2024-12-25 02:40 UTC, wengzhe commented on testing/nettest/tcp/test_tcp_connect_01.c
> +int tcp_connect_setup_01(FAR void **state)
`test_tcp_connect_ipv4_setup` ?

2024-12-25 02:40 UTC, wengzhe commented on testing/nettest/tcp/test_tcp_connect_01.c
> +void test_tcp_connect_ipv4_01(FAR void **state)
What's the rule of our case name? `test_tcp_connect_ipv4` or `test_tcp_connect_ipv4_01` ?

2024-12-25 02:40 UTC, wengzhe commented on testing/nettest/tcp/test_tcp_connect_01.c
> + * apps/testing/nettest/tcp/test_tcp_connect_01.c
`test_tcp_connect_ipv4.c`?

2024-12-25 02:40 UTC, wengzhe commented on testing/nettest/tcp/test_tcp_common.c
> +int tcp_group_setup(FAR void **state)
`test_tcp_group_setup`

2024-12-25 02:40 UTC, wengzhe commented on testing/nettest/tcp/test_tcp_common.c
> +int tcp_group_teardown(FAR void **state)
`test_tcp_group_teardown`

2024-12-25 02:47 UTC, closed without merging